### ISSUE TITLE
imagedestroy() expects parameter 1 to be resource

### ISSUE THREAD

**Issue by akroii** [derhaeuptling/contao-lazy-images#3]
Ich verwende lazy-sizes 2.0.0 Build 7 (mit ER2) unter Contao 3.5.12 und erhalte folgende Fehlermeldung:
```
PHP Warning: imagedestroy() expects parameter 1 to be resource, boolean given in /htdocs/contao-3.5.25/system/modules/lazy-images/src/DerHaeuptling/classes/LazySizes.php on line 270
#0 [internal function]: __error(2, 'imagedestroy() ...', '/homepages/27/d...', 270, Array)
#1 /htdocs/contao-3.5.25/system/modules/lazy-images/src/DerHaeuptling/classes/LazySizes.php(270): imagedestroy(false)
#2 /htdocs/contao-3.5.25/system/modules/lazy-images/src/DerHaeuptling/classes/LazySizes.php(115): Contao\LazySizes::_gdTransparentImage(NULL, NULL)
#3 /htdocs/contao-3.5.25/system/modules/lazy-images/src/DerHaeuptling/classes/LazySizes.php(73): Contao\LazySizes->_preparePlaceholder()
#4 /htdocs/contao-3.5.25/system/modules/core/library/Contao/Template.php(273): Contao\LazySizes->init(Object(Contao\FrontendTemplate))
#5 /htdocs/contao-3.5.25/system/modules/core/classes/FrontendTemplate.php(46): Contao\Template->parse()
#6 /htdocs/contao-3.5.25/system/modules/core/library/Contao/BaseTemplate.php(281): Contao\FrontendTemplate->parse()
#7 /htdocs/contao-3.5.25/templates/news_latest.html5(11): Contao\BaseTemplate->insert('picture_default', Array)
#8 /htdocs/contao-3.5.25/system/modules/core/library/Contao/BaseTemplate.php(88): include('/homepages/27/d...')
#9 /htdocs/contao-3.5.25/system/modules/core/library/Contao/Template.php(277): Contao\BaseTemplate->parse()
#10 /htdocs/contao-3.5.25/system/modules/core/classes/FrontendTemplate.php(46): Contao\Template->parse()
#11 /htdocs/contao-3.5.25/system/modules/news/modules/ModuleNews.php(218): Contao\FrontendTemplate->parse()
#12 /htdocs/contao-3.5.25/system/modules/news/modules/ModuleNews.php(247): Contao\ModuleNews->parseArticle(Object(NewsCategories\NewsModel), false, ' even', 3)
#13 /htdocs/contao-3.5.25/system/modules/news/modules/ModuleNewsArchive.php(198): Contao\ModuleNews->parseArticles(Object(Contao\Model\Collection))
#14 /htdocs/contao-3.5.25/system/modules/core/modules/Module.php(287): Contao\ModuleNewsArchive->compile()
#15 /htdocs/contao-3.5.25/system/modules/news/modules/ModuleNewsArchive.php(70): Contao\Module->generate()
#16 /htdocs/contao-3.5.25/system/modules/news_categories/modules/ModuleNewsArchive.php(34): Contao\ModuleNewsArchive->generate()
#17 /htdocs/contao-3.5.25/system/modules/core/elements/ContentModule.php(59): NewsCategories\ModuleNewsArchive->generate()
#18 /htdocs/contao-3.5.25/system/modules/core/library/Contao/Controller.php(484): Contao\ContentModule->generate()
#19 /htdocs/contao-3.5.25/system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#20 /htdocs/contao-3.5.25/system/modules/core/modules/Module.php(287): Contao\ModuleArticle->compile()
#21 /htdocs/contao-3.5.25/system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
#22 /htdocs/contao-3.5.25/system/modules/core/library/Contao/Controller.php(417): Contao\ModuleArticle->generate(false)
#23 /htdocs/contao-3.5.25/system/modules/core/library/Contao/Controller.php(277): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
#24 /htdocs/contao-3.5.25/system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
#25 /htdocs/contao-3.5.25/system/modules/core/controllers/FrontendIndex.php(285): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#26 /htdocs/contao-3.5.25/index.php(20): Contao\FrontendIndex->run()
#27 {main}
```

Bisher konnte ich noch nicht erkennen wie der Fehler zustande kommt.

**Comment by Metis77** [comment]
Probier mal bitte den aktuellen Master hier auf GitHub.
Löst dieser diesen Fehler bei dir?

**Comment by akroii** [comment]
Ich verwende das ER2. Gibt es da auch eine Möglichkeit den Fehler zu beheben?

**Comment by Metis77** [comment]
Ich habe soeben 2.0.1 im ER freigegeben.
Dieser Release enthält den letzt Commit – behebt der dein Problem?

**Comment by akroii** [comment]
Danke, Problem durch 2.0.1 gelöst. Vielen Dank!
